#!/bin/bash
xhost +
docker build --build-arg USERNAME=$(whoami) --build-arg USER_UID=$(id -u) -t vicharaka-noetic .
docker run -it --net=host --gpus all     --env="NVIDIA_DRIVER_CAPABILITIES=all"     --env="DISPLAY"     --env="QT_X11_NO_MITSHM=1"     --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"   --volume="$PWD:/home/$(whoami)/:rw" --user="$(whoami)" vicharaka-noetic     bash 
